package toolstore

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"strings"
	"time"
)

const reconciliationRunColumns = `id, run_key, kind, status, window_start, window_end,
	started_at, finished_at, scanned_count, matched_count, discrepancy_count,
	discrepancy_minor, currency, COALESCE(summary_json, ''), error_code,
	error_message, created_at, updated_at`

func (s *Store) CreateReconciliationRun(ctx context.Context, input ReconciliationRunInput) (ReconciliationRun, error) {
	return s.createReconciliationRun(ctx, s.db, input)
}

func (s *Store) createReconciliationRun(ctx context.Context, executor execQueryer, input ReconciliationRunInput) (ReconciliationRun, error) {
	var err error
	if input.RunKey, err = requireText("run_key", input.RunKey); err != nil {
		return ReconciliationRun{}, err
	}
	if input.Kind, err = requireText("kind", input.Kind); err != nil {
		return ReconciliationRun{}, err
	}
	if !validReconciliationStatus(input.Status) {
		return ReconciliationRun{}, fmt.Errorf("%w: unsupported reconciliation status %q", ErrInvalid, input.Status)
	}
	input.WindowStart = input.WindowStart.UTC().Truncate(time.Millisecond)
	input.WindowEnd = input.WindowEnd.UTC().Truncate(time.Millisecond)
	if err := validateWindow(input.WindowStart, input.WindowEnd); err != nil {
		return ReconciliationRun{}, err
	}
	if err := validateCounts(input.ScannedCount, input.MatchedCount, input.DiscrepancyCount); err != nil {
		return ReconciliationRun{}, err
	}
	if input.Currency, err = validateCurrency(input.Currency); err != nil {
		return ReconciliationRun{}, err
	}
	summary, err := normalizedJSON("summary_json", input.SummaryJSON)
	if err != nil {
		return ReconciliationRun{}, err
	}
	now := s.clock()
	startedAt := normalizeOccurred(input.StartedAt, now)
	finishedAt := normalizeOptionalTime(input.FinishedAt)
	if err := validateRunFinish(input.Status, startedAt, finishedAt); err != nil {
		return ReconciliationRun{}, err
	}
	input.StartedAt = startedAt
	input.FinishedAt = finishedAt
	input.SummaryJSON = summary
	input.ErrorCode = strings.TrimSpace(input.ErrorCode)
	input.ErrorMessage = strings.TrimSpace(input.ErrorMessage)
	result, err := executor.ExecContext(ctx, `INSERT INTO reconciliation_runs(
		run_key, kind, status, window_start, window_end, started_at, finished_at,
		scanned_count, matched_count, discrepancy_count, discrepancy_minor,
		currency, summary_json, error_code, error_message, created_at, updated_at
	) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
	ON CONFLICT(run_key) DO NOTHING`,
		input.RunKey, input.Kind, input.Status, dbTime(input.WindowStart), dbTime(input.WindowEnd),
		dbTime(startedAt), nullableDBTime(finishedAt), input.ScannedCount,
		input.MatchedCount, input.DiscrepancyCount, input.DiscrepancyMinor,
		input.Currency, summary, input.ErrorCode, input.ErrorMessage, dbTime(now), dbTime(now))
	if err != nil {
		return ReconciliationRun{}, fmt.Errorf("create reconciliation run: %w", err)
	}
	rows, err := result.RowsAffected()
	if err != nil {
		return ReconciliationRun{}, fmt.Errorf("read reconciliation run result: %w", err)
	}
	if rows == 0 {
		existing, getErr := getReconciliationRun(ctx, executor, "run_key", input.RunKey)
		if getErr != nil {
			return ReconciliationRun{}, getErr
		}
		if !reconciliationRunMatchesFingerprint(existing, input) {
			return ReconciliationRun{}, fmt.Errorf("%w: run key belongs to a different reconciliation run", ErrConflict)
		}
		return existing, nil
	}
	id, err := result.LastInsertId()
	if err != nil {
		return ReconciliationRun{}, fmt.Errorf("read reconciliation run id: %w", err)
	}
	return getReconciliationRun(ctx, executor, "id", id)
}

func reconciliationRunMatchesFingerprint(item ReconciliationRun, input ReconciliationRunInput) bool {
	return reconciliationFingerprintForRun(item) == reconciliationFingerprintForInput(input)
}

// reconciliationRunFingerprint is the immutable identity of a logical run.
// Lifecycle state and evidence (status, timestamps, counts, summary and errors)
// are deliberately excluded: they can be generated by the store or advance
// after creation, and therefore cannot safely participate in replay matching.
type reconciliationRunFingerprint struct {
	RunKey      string
	Kind        string
	WindowStart int64
	WindowEnd   int64
	Currency    string
}

func reconciliationFingerprintForRun(item ReconciliationRun) reconciliationRunFingerprint {
	return reconciliationRunFingerprint{
		RunKey:      item.RunKey,
		Kind:        item.Kind,
		WindowStart: item.WindowStart.UnixMilli(),
		WindowEnd:   item.WindowEnd.UnixMilli(),
		Currency:    item.Currency,
	}
}

func reconciliationFingerprintForInput(input ReconciliationRunInput) reconciliationRunFingerprint {
	return reconciliationRunFingerprint{
		RunKey:      strings.TrimSpace(input.RunKey),
		Kind:        strings.TrimSpace(input.Kind),
		WindowStart: input.WindowStart.UTC().Truncate(time.Millisecond).UnixMilli(),
		WindowEnd:   input.WindowEnd.UTC().Truncate(time.Millisecond).UnixMilli(),
		Currency:    strings.ToUpper(strings.TrimSpace(input.Currency)),
	}
}

func (s *Store) GetReconciliationRun(ctx context.Context, id int64) (ReconciliationRun, error) {
	if id <= 0 {
		return ReconciliationRun{}, fmt.Errorf("%w: reconciliation run id must be positive", ErrInvalid)
	}
	return getReconciliationRun(ctx, s.db, "id", id)
}

func (s *Store) GetReconciliationRunByKey(ctx context.Context, key string) (ReconciliationRun, error) {
	key = strings.TrimSpace(key)
	if key == "" {
		return ReconciliationRun{}, fmt.Errorf("%w: run key is required", ErrInvalid)
	}
	return getReconciliationRun(ctx, s.db, "run_key", key)
}

func getReconciliationRun(ctx context.Context, queryer queryRower, column string, value any) (ReconciliationRun, error) {
	item, err := scanReconciliationRun(queryer.QueryRowContext(ctx,
		"SELECT "+reconciliationRunColumns+" FROM reconciliation_runs WHERE "+column+" = ?", value))
	if err != nil {
		if err == sql.ErrNoRows {
			return ReconciliationRun{}, ErrNotFound
		}
		return ReconciliationRun{}, fmt.Errorf("get reconciliation run: %w", err)
	}
	return item, nil
}

// UpdateReconciliationRun advances a running job. Terminal runs are immutable,
// which keeps reconciliation evidence stable after publication.
func (s *Store) UpdateReconciliationRun(ctx context.Context, update ReconciliationRunUpdate) (ReconciliationRun, error) {
	if update.ID <= 0 {
		return ReconciliationRun{}, fmt.Errorf("%w: reconciliation run id must be positive", ErrInvalid)
	}
	if !validReconciliationStatus(update.Status) {
		return ReconciliationRun{}, fmt.Errorf("%w: unsupported reconciliation status %q", ErrInvalid, update.Status)
	}
	if err := validateCounts(update.ScannedCount, update.MatchedCount, update.DiscrepancyCount); err != nil {
		return ReconciliationRun{}, err
	}
	summary, err := normalizedJSON("summary_json", update.SummaryJSON)
	if err != nil {
		return ReconciliationRun{}, err
	}
	finishedAt := normalizeOptionalTime(update.FinishedAt)

	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return ReconciliationRun{}, fmt.Errorf("begin reconciliation update: %w", err)
	}
	defer func() { _ = tx.Rollback() }()
	current, err := getReconciliationRun(ctx, tx, "id", update.ID)
	if err != nil {
		return ReconciliationRun{}, err
	}
	if current.Status != ReconciliationRunning {
		return ReconciliationRun{}, fmt.Errorf("%w: terminal reconciliation runs are immutable", ErrConflict)
	}
	if err := validateRunFinish(update.Status, current.StartedAt, finishedAt); err != nil {
		return ReconciliationRun{}, err
	}
	result, err := tx.ExecContext(ctx, `UPDATE reconciliation_runs SET
		status = ?, finished_at = ?, scanned_count = ?, matched_count = ?,
		discrepancy_count = ?, discrepancy_minor = ?, summary_json = ?,
		error_code = ?, error_message = ?, updated_at = ?
		WHERE id = ? AND status = 'running'`,
		update.Status, nullableDBTime(finishedAt), update.ScannedCount,
		update.MatchedCount, update.DiscrepancyCount, update.DiscrepancyMinor,
		summary, strings.TrimSpace(update.ErrorCode), strings.TrimSpace(update.ErrorMessage),
		dbTime(s.clock()), update.ID)
	if err != nil {
		return ReconciliationRun{}, fmt.Errorf("update reconciliation run: %w", err)
	}
	rows, err := result.RowsAffected()
	if err != nil {
		return ReconciliationRun{}, fmt.Errorf("read reconciliation update result: %w", err)
	}
	if rows == 0 {
		return ReconciliationRun{}, fmt.Errorf("%w: reconciliation run changed concurrently", ErrConflict)
	}
	item, err := getReconciliationRun(ctx, tx, "id", update.ID)
	if err != nil {
		return ReconciliationRun{}, err
	}
	if err := tx.Commit(); err != nil {
		return ReconciliationRun{}, fmt.Errorf("commit reconciliation update: %w", err)
	}
	return item, nil
}

func (s *Store) ListReconciliationRuns(ctx context.Context, filter ReconciliationRunFilter) (ReconciliationRunPage, error) {
	limit := pageLimit(filter.Limit)
	var query strings.Builder
	query.WriteString("SELECT ")
	query.WriteString(reconciliationRunColumns)
	query.WriteString(" FROM reconciliation_runs WHERE 1=1")
	args := make([]any, 0, 4)
	if strings.TrimSpace(filter.Kind) != "" {
		query.WriteString(" AND kind = ?")
		args = append(args, strings.TrimSpace(filter.Kind))
	}
	if filter.Status != "" {
		if !validReconciliationStatus(filter.Status) {
			return ReconciliationRunPage{}, fmt.Errorf("%w: unsupported reconciliation status %q", ErrInvalid, filter.Status)
		}
		query.WriteString(" AND status = ?")
		args = append(args, filter.Status)
	}
	if filter.BeforeID > 0 {
		query.WriteString(" AND id < ?")
		args = append(args, filter.BeforeID)
	}
	query.WriteString(" ORDER BY id DESC LIMIT ?")
	args = append(args, limit+1)

	rows, err := s.db.QueryContext(ctx, query.String(), args...)
	if err != nil {
		return ReconciliationRunPage{}, fmt.Errorf("list reconciliation runs: %w", err)
	}
	defer rows.Close()
	items := make([]ReconciliationRun, 0, limit+1)
	for rows.Next() {
		item, err := scanReconciliationRun(rows)
		if err != nil {
			return ReconciliationRunPage{}, fmt.Errorf("scan reconciliation run: %w", err)
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return ReconciliationRunPage{}, fmt.Errorf("iterate reconciliation runs: %w", err)
	}
	items, cursor, more := pageResult(items, limit, func(item ReconciliationRun) int64 { return item.ID })
	return ReconciliationRunPage{Items: items, NextCursor: cursor, HasMore: more}, nil
}

func validateCounts(scanned, matched, discrepancy int64) error {
	if scanned < 0 || matched < 0 || discrepancy < 0 {
		return fmt.Errorf("%w: reconciliation counts cannot be negative", ErrInvalid)
	}
	if matched > scanned || discrepancy > scanned {
		return fmt.Errorf("%w: matched and discrepancy counts cannot exceed scanned_count", ErrInvalid)
	}
	return nil
}

func validateRunFinish(status ReconciliationStatus, startedAt time.Time, finishedAt *time.Time) error {
	if status == ReconciliationRunning {
		if finishedAt != nil {
			return fmt.Errorf("%w: running reconciliations cannot have finished_at", ErrInvalid)
		}
		return nil
	}
	if finishedAt == nil {
		return fmt.Errorf("%w: terminal reconciliations require finished_at", ErrInvalid)
	}
	if finishedAt.Before(startedAt) {
		return fmt.Errorf("%w: finished_at cannot be before started_at", ErrInvalid)
	}
	return nil
}

func scanReconciliationRun(row rowScanner) (ReconciliationRun, error) {
	var item ReconciliationRun
	var windowStart, windowEnd, startedAt, createdAt, updatedAt int64
	var finishedAt sql.NullInt64
	var summary string
	err := row.Scan(&item.ID, &item.RunKey, &item.Kind, &item.Status, &windowStart,
		&windowEnd, &startedAt, &finishedAt, &item.ScannedCount, &item.MatchedCount,
		&item.DiscrepancyCount, &item.DiscrepancyMinor, &item.Currency, &summary,
		&item.ErrorCode, &item.ErrorMessage, &createdAt, &updatedAt)
	if err != nil {
		return ReconciliationRun{}, err
	}
	item.WindowStart = fromDBTime(windowStart)
	item.WindowEnd = fromDBTime(windowEnd)
	item.StartedAt = fromDBTime(startedAt)
	item.CreatedAt = fromDBTime(createdAt)
	item.UpdatedAt = fromDBTime(updatedAt)
	if finishedAt.Valid {
		value := fromDBTime(finishedAt.Int64)
		item.FinishedAt = &value
	}
	if summary != "" {
		item.SummaryJSON = json.RawMessage(summary)
	}
	return item, nil
}
